export enum AccountType {
  COMPLIANCE_ASSURANCE_SURRENDER = 'Compliance Assurance Surrender Account',
  ENFORCEMENT_SURRENDER = 'Enforcement Surrender Account',
  FACILITY = 'Facility Account',
  GENERAL = 'General Account',
  OVERDRAFT = 'Overdraft Account',
  EPA_RESERVE = 'EPA Reserve Account',
  STATE_EARLY_REDUCTION_RESERVE = 'State Early Reduction Reserve Account',
  STATE_GENERAL_RESERVE = 'State General Reserve Account',
  STATE_HOLDING = 'State Holding Account',
  NEW_UNIT_SET_ASIDE_RESERVE = 'New Unit Set Aside Reserve Account',
  STATE_OPT_IN_RESERVE = 'State Opt-In Reserve Account',
  STATE_OTHER_RESERVE = 'State Other Reserve Account',
  STATE_PRIMARY_RESERVE = 'State Primary Reserve Account',
  STATE_RETIREMENT = 'State Retirement Account',
  SURRENDER = 'Surrender Account',
  UNIT = 'Unit Account',
  VOLUNTARY_SURRENDER = 'Voluntary Surrender Account',
}
