export enum AllowanceProgram {
  ARP = 'ARP',
  CAIRNOX = 'CAIRNOX',
  CAIROS = 'CAIROS',
  CAIRSO2 = 'CAIRSO2',
  CSNOX = 'CSNOX',
  CSNOXOS = 'CSNOXOS',
  CSOSG1 = 'CSOSG1',
  CSOSG2 = 'CSOSG2',
  CSSO2G1 = 'CSSO2G1',
  CSSO2G2 = 'CSSO2G2',
  NBP = 'NBP',
  OTC = 'OTC',
  TXSO2 = 'TXSO2',
}
