export enum ExcludeApportionedEmissions {
  CO2_RATE = "co2Rate",
  COUNT_OP_TIME = "countOpTime",
  GROSS_LOAD = "grossLoad",
  HG_CONTROL_INFO = "hgControlInfo",
  NOX_CONTROL_INFO = "noxControlInfo",
  PM_CONTROL_INFO = "pmControlInfo",
  PRIMARY_FUEL_INFO = "primaryFuelInfo",
  SECONDARY_FUEL_INFO = "secondaryFuelInfo",
  SO2_CONTROL_INFO = "so2ControlInfo",
  SO2_RATE = "so2Rate",
  STEAM_LOAD = "steamLoad",
  SUM_OP_TIME = "sumOpTime",
  UNIT_TYPE = "unitType",
  UNIT_ID = 'unit_id',
}
