export enum ExcludeHourlyMatsApportionedEmissions {
  HCL_INPUT_RATE = "hclInputRate",
  HCL_MASS_MEASURE_FLAG = "hclMassMeasureFlg",
  HCL_OUTPUT_RATE = "hclOutputRate",
  HF_INPUT_RATE = "hfInputRate",
  HF_MASS_MEASURE_FLAG = "hfMassMeasureFlg",
  HF_OUTPUT_RATE = "hfOutputRate",
  HG_CONTROL_INFO = "hgControlInfo",
  HG_INPUT_RATE = "hgInputRate",
  HG_MASS_MEASURE_FLAG = "hgMassMeasureFlg",
  HG_OUTPUT_RATE = "hgOutputRate",
  MATS_GROSS_LOAD = "matsGrossLoad",
  NOX_CONTROL_INFO = "noxControlInfo",
  OP_TIME = "opTime",
  PM_CONTROL_INFO = "pmControlInfo",
  PRIMARY_FUEL_TYPE = "primaryFuelInfo",
  SECONDARY_FUEL_TYPE = "secondaryFuelInfo",
  SO2_CONTROL_INFO = "so2ControlInfo",
  STEAM_LOAD = "steamLoad",
  UNIT_TYPE = "unitType",
  UNIT_ID = 'unit_id',
}
