export enum ExcludeHourlyApportionedEmissions {
  CO2_MASS_MEASURE_FLAG = "co2MassMeasureFlg",
  CO2_RATE = "co2Rate",
  CO2_RATE_MEASURE_FLAG = "co2RateMeasureFlg",
  GROSS_LOAD = "grossLoad",
  HG_CONTROL_INFO = "hgControlInfo",
  NOX_CONTROL_INFO = "noxControlInfo",
  NOX_MASS_MEASURE_FLAG = "noxMassMeasureFlg",
  NOX_RATE_MEASURE_FLAG = "noxRateMeasureFlg",
  OP_TIME = "opTime",
  PM_CONTROL_INFO = "pmControlInfo",
  PRIMARY_FUEL_INFO = "primaryFuelInfo",
  SECONDARY_FUEL_INFO = "secondaryFuelInfo",
  SO2_CONTROL_INFO = "so2ControlInfo",
  SO2_MASS_MEASURE_FLAG = "so2MassMeasureFlg",
  SO2_RATE = "so2Rate",
  SO2_RATE_MEASURE_FLAG = "so2RateMeasureFlg",
  STEAM_LOAD = "steamLoad",
  UNIT_TYPE = "unitType",
}
