"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ControlTechnology = void 0;
var ControlTechnology;
(function (ControlTechnology) {
    ControlTechnology["ADDITIVES_TO_ENHANCE"] = "Additives to Enhance PAC and Existing Equipment Performance";
    ControlTechnology["AMMONIA_INJECTION"] = "Ammonia Injection";
    ControlTechnology["BAGHOUSE"] = "Baghouse";
    ControlTechnology["CATALYST"] = "Catalyst (gold, palladium, or other) used to oxidize mercury";
    ControlTechnology["COMBUSTION_MODIFICATION"] = "Combustion Modification/Fuel Reburning";
    ControlTechnology["CYCLONE"] = "Cyclone";
    ControlTechnology["DRY_LIME_FGD"] = "Dry Lime FGD";
    ControlTechnology["DRY_LOW_NOX"] = "Dry Low NOx Burners";
    ControlTechnology["DRY_SORBENT"] = "Dry Sorbent Injection";
    ControlTechnology["DUAL_ALKALI"] = "Dual Alkali";
    ControlTechnology["ELECTROSTATIC_PRECIPITATOR"] = "Electrostatic Precipitator";
    ControlTechnology["FLUIDIZED_BED_LIMESTONE"] = "Fluidized Bed Limestone Injection";
    ControlTechnology["HALOGENATED_PAC_SORBENT"] = "Halogenated PAC Sorbent Injection";
    ControlTechnology["HYBRID_ESP"] = "Hybrid ESP";
    ControlTechnology["LOW_NOX_DRY_BOTTOM"] = "Low NOx Burner Technology (Dry Bottom only)";
    ControlTechnology["LOW_NOX_CC_OFA"] = "Low NOx Burner Technology w/ Closed-coupled OFA";
    ControlTechnology["LOW_NOX_CC_SEPARATED_OFA"] = "Low NOx Burner Technology w/ Closed-coupled/Separated OFA";
    ControlTechnology["LOW_NOX_OVERFIRE"] = "Low NOx Burner Technology w/ Overfire Air";
    ControlTechnology["LOW_NOX_SEPARATED_OFA"] = "Low NOx Burner Technology w/ Separated OFA";
    ControlTechnology["LOW_NOX_CELL"] = "Low NOx Cell Burner";
    ControlTechnology["MAGNESIUM_OXIDE"] = "Magnesium Oxide";
    ControlTechnology["OTHER"] = "Other";
    ControlTechnology["OTHER_SORBENT"] = "Other (Non PAC) Sorbent Injection";
    ControlTechnology["OVERFIRE_AIR"] = "Overfire Air";
    ControlTechnology["REGENERATIVE_ACTIVATED"] = "Regenerative Activated Coke Technology";
    ControlTechnology["SELECTIVE_CATALYTIC"] = "Selective Catalytic Reduction";
    ControlTechnology["SELECTIVE_NON_CATALYTIC"] = "Selective Non-catalytic Reduction";
    ControlTechnology["SODIUM_BASED"] = "Sodium Based";
    ControlTechnology["STEAM_INJECTION"] = "Steam Injection";
    ControlTechnology["UNTREATED_PAC"] = "Untreated PAC Sorbent Injection";
    ControlTechnology["WATER_INJECTION"] = "Water Injection";
    ControlTechnology["WET_ESP"] = "Wet ESP";
    ControlTechnology["WET_LIME_FGD"] = "Wet Lime FGD";
    ControlTechnology["WET_LIMESTONE"] = "Wet Limestone";
    ControlTechnology["WET_SCRUBBER"] = "Wet Scrubber";
})(ControlTechnology = exports.ControlTechnology || (exports.ControlTechnology = {}));
//# sourceMappingURL=control-technology.enum.js.map